name: Run Central Validation

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  call-validator:
    uses: Jayanth-Thunga-RH/validation-workflows/.github/workflows/validate.yml@main
    with:
      branch: ${{ github.ref_name }}
