# .github/workflows/validate.yml

name: Validate UiPath Dependencies

on:
  push:
    branches:
      - '**'           # Runs on push to ANY branch
  workflow_dispatch:   # Allows manual run from GitHub UI

jobs:
  validate-deps:
    uses: revivalhealthllc/validation-workflows/.github/workflows/validate-uipath.yml@main
